name: sample workflow to understand the basics
run-name: ${{ github.actor }} have triggered this action by ${{ github.event_name }} in ${{ github.ref }}
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    job-a:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job A has run successfully"
    job-b:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Job B has run successfully"
