name: sample workflow to understand the basics
run-name: ${{ github.actor }} have triggered this action by ${{ github.event_name }} in ${{ github.ref }}
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    job-a:
        runs-on: ubuntu-latest
        outputs:
            output-a: ${{ steps.random-num.outputs.Random_Num }}
        steps:
            - name: Calculate Random Num in the event of a PR
              id: random-num
              if: github.event_name == 'pull_request'
              run: |
                  Random_Num=$((PRNUM%ENVCOUNT))
                  echo "Random_Num=$Random_Num"
                  echo "Random_Num=$Random_Num" >> $GITHUB_OUTPUT
    job-b:
        runs-on: ubuntu-latest
        needs: ["job-a"]
        steps:
            - run: echo "Job B has run successfully and got input - ${{ needs.job-a.outputs.output-a }}"
