name: sample workflow to understand the basics
run-name: ${{ github.actor }} have triggered this action by ${{ github.event_name }} in ${{ github.ref }}
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    job-a:
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: "step 1 of ${{ github.job }}"
              run: echo "Job A has run successfully"
    job-b:
        runs-on: ubuntu-latest
        needs: ["job-a"]
        steps:
            - run: echo "Job B has run successfully"
